# Generated by Django 4.0 on 2022-09-08 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_post_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='download_link',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
