# Generated by Django 4.0 on 2022-09-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_remove_post_total_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(max_length=216, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=216, unique=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='title',
            field=models.CharField(max_length=216, unique=True),
        ),
    ]
