# Generated by Django 4.0 on 2022-09-08 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_remove_content_post_remove_post_season_season_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='total_content',
        ),
    ]
